GODproject/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from rest_framework.authtoken import views
from summaryapp.api import CrawlingList, CrawlingDetail

urlpatterns = [

    path("admin/", admin.site.urls),
    path("summarys/", include('summaryapp.urls')),
    path("profiles/", include('profileapp.urls')),
    path('api/crawling_list', CrawlingList.as_view(), name='crawling_list'),
    path('api/crawling_list/<int:pk>', CrawlingDetail.as_view(), name='crawling_detail'),
    # path('api/auth', views.obtain_auth_token, name='user_auth-create'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

profileapp/urls.py
from django.urls import path

from profileapp.views import ProfileCreateView, ProfileUpdateView

app_name = 'profileapp'

urlpatterns = [
    path('create/', ProfileCreateView.as_view(), name='create'),
    path('update<int:pk>/', ProfileUpdateView.as_view(), name='update'),
]

summaryapp/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path

from summaryapp.views import index, AccountCreateView, AccountDetailView, AccountUpdateView, AccountDeleteView, \
    crawling_test

app_name = "summaryapp"

urlpatterns = [
    path('index/', index, name='index'),
    path('crawling/', crawling_test, name='crawling'),

    path('login/', LoginView.as_view(template_name='summaryapp/login.html'), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),

    path('create/', AccountCreateView.as_view(), name='create'),
    path('detail/<int:pk>', AccountDetailView.as_view(), name='detail'),
    path('update/<int:pk>', AccountUpdateView.as_view(), name='update'),
    path('delete/<int:pk>', AccountDeleteView.as_view(), name='delete'),
]

profileapp/models.py
from django.contrib.auth.models import User
from django.db import models

# Create your models here.
class Profile(models.Model):
    # OneToOneField, User와 Profile 객체를 1:1로 연결시켜줌
    user = models.OneToOneField(User, on_delete=models.CASCADE, related_name='profile')

    # upload_to : 서버에 들어온 Image를 저장시킬 위치 지정
    image = models.ImageField(upload_to='profile/', null=True)

    # unique : 객체 안에서 nickname는 1개여야 한다.(중복 x)
    nickname = models.CharField(max_length=20, unique=True, null=True)
    message = models.CharField(max_length=100, null=True)

summaryapp/models.py
from django.db import models

# Create your models here.
class Crawling(models.Model):
    press = models.CharField(max_length=10, null=True)
    title = models.CharField(max_length=25, null=True)
    article = models.TextField()

    def __str__(self):
        return self.title

class Summary(models.Model):
    text = models.TextField()

    def __str__(self):
        return self.text


class Godsummary(models.Model):
    press = models.CharField(max_length=10, null=True)
    title = models.TextField()
    category = models.CharField(max_length=10, null=True)
    article = models.TextField()
    datetime = models.DateTimeField()
    link = models.TextField()

class Article(models.Model):
    title = models.CharField(max_length=25, null=True)
    article = models.TextField()


class Emd_vector(models.Model):
    rank = models.ForeignKey(Article, on_delete=models.CASCADE)
    emd_vector = models.IntegerField()

profileapp/forms.py
from django.forms import ModelForm

from profileapp.models import Profile


class ProfileCreationForm(ModelForm): # modelform을 상속
    class Meta:
        model = Profile # 사용할 모델 지정
        fields = ['image', 'nickname', 'message'] # 사용할 필드 지정

summaryapp/forms.py
from django.contrib.auth.forms import UserCreationForm

class AccountUpdateForm(UserCreationForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        self.fields['username'].disabled = True

profileapp/views.py
from django.shortcuts import render
from django.urls import reverse_lazy, reverse
from django.utils.decorators import method_decorator
from django.views.generic import CreateView, UpdateView

from profileapp.decorators import profile_ownership_required
from profileapp.forms import ProfileCreationForm
from profileapp.models import Profile


# Create your views here.
class ProfileCreateView(CreateView):
    model = Profile
    context_object_name = 'target_profile'
    form_class = ProfileCreationForm
    template_name = 'profileapp/create.html'

    def form_valid(self, form):
        temp_profile = form.save(commit=False)
        temp_profile.user = self.request.user
        temp_profile.save()
        return super().form_valid(form)

    def get_success_url(self):
        return reverse('summaryapp:detail', kwargs={'pk': self.object.user.pk})

@method_decorator(profile_ownership_required, 'get')
@method_decorator(profile_ownership_required, 'post')
class ProfileUpdateView(UpdateView):
    model = Profile
    context_object_name = 'target_profile'
    form_class = ProfileCreationForm
    template_name = 'profileapp/update.html'

    def get_success_url(self):
        return reverse('summaryapp:detail', kwargs={'pk': self.object.user.pk})

summaryapp/views.py
from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django.http import HttpResponse, HttpResponseRedirect, HttpResponseForbidden
from django.shortcuts import render
from django.urls import reverse_lazy, reverse
from django.utils.decorators import method_decorator
from django.views.generic import CreateView, DetailView, UpdateView, DeleteView

from khj.crawling import get_news
from summaryapp.decorators import account_ownership_required
from summaryapp.forms import AccountUpdateForm
from summaryapp.models import Summary, Crawling

has_ownership = [account_ownership_required, login_required]
# Create your views here.

@login_required(login_url='/summarys/login/')
def index(request):
    if request.method == 'POST':
        temp = request.POST.get('summary_input')
        new_summary = Summary()
        new_summary.text = temp
        new_summary.save()
        return render(request, 'summaryapp/index.html', context={'summary_output' : new_summary})
    else:
        return render(request, 'summaryapp/index.html', context={'text' : 'get Method!'})

def crawling_test(request):
    global crawling_output1, crawling_output2, crawling_output3
    if request.method == 'POST':
        subs = request.POST.get('crawling_input')
        crawling_df = get_news(subs)
        for i in range(0, crawling_df.shape[0]):
            if i != 1:
                row = crawling_df.iloc[i]
                crawling_output1 = row['press']
                crawling_output2 = row['title']
                crawling_output3 = row['article']
            else:
                break
        new_crawling = Crawling(press=crawling_output1, title=crawling_output2, article=crawling_output3)
        new_crawling.text = crawling_output3
        new_crawling.save()

        return render(request, 'summaryapp/index.html', context={'crawling_data' : new_crawling})
    else:
        return render(request, 'summaryapp/index.html', context={'text' : '내용이 없습니다.'})

class AccountCreateView(CreateView):
    model = User
    form_class = UserCreationForm # User 모델을 만들 때 사용할 Form 가져오기
    success_url = reverse_lazy('summaryapp:index') # 계정 생성 성공시 어느 경로로 연결을 할것인지 지정
    template_name = 'summaryapp/create.html' # 어느 HTML을 사용하요 Form을 볼지 지정


class AccountDetailView(DetailView):
    model = User
    context_object_name = 'target_user'
    template_name = 'summaryapp/detail.html'


@method_decorator(has_ownership, 'get') # 일반 함수에 사용하는 데코레이터를 메소드에서 사용 할 수 있도록 변환
@method_decorator(has_ownership, 'post') # 일반 함수에 사용하는 데코레이터를 메소드에서 사용 할 수 있도록 변환
class AccountUpdateView(UpdateView):
    model = User
    context_object_name = 'target_user'
    form_class = AccountUpdateForm # User 모델을 만들 때 사용할 Form 가져오기
    success_url = reverse_lazy('summaryapp:index') # 계정 생성 성공시 어느 경로로 연결을 할것인지 지정
    template_name = 'summaryapp/update.html' # 어느 HTML을 사용하요 Form을 볼지 지정


@method_decorator(has_ownership, 'get') # 일반 함수에 사용하는 데코레이터를 메소드에서 사용 할 수 있도록 변환
@method_decorator(has_ownership, 'post') # 일반 함수에 사용하는 데코레이터를 메소드에서 사용 할 수 있도록 변환
class AccountDeleteView(DeleteView):
    model = User
    context_object_name = 'target_user'
    success_url = reverse_lazy('summaryapp:login')  # 계정 생성 성공시 어느 경로로 연결을 할것인지 지정
    template_name = 'summaryapp/delete.html'  # 어느 HTML을 사용하요 Form을 볼지 지정

profileapp/templates/profileapp/create.html
{% extends 'base.html' %}
{% load bootstrap4 %}
{% block content %}

<div style="text-align: center; max-width: 500px; margin: 4rem auto;">
  <div class="mb-4">
    <h3>Profile Create</h3>
  </div>
  <form action="{% url 'profileapp:create' %}" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {% bootstrap_form form %}
    <input type="submit" class="btn btn-dark rounded-pill col-6 mt-3" value="회원가입">
  </form>
</div>
{% endblock %}

profileapp/templates/profileapp/update.html
{% extends 'base.html' %}
{% load bootstrap4 %}
{% block content %}

<div style="text-align: center; max-width: 500px; margin: 4rem auto;">
  <div class="mb-4">
    <h3>Update Profile</h3>
  </div>
  <form action="{% url 'profileapp:update' pk=target_profile.pk%}" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {% bootstrap_form form %}
    <input type="submit" class="btn btn-dark rounded-pill col-6 mt-3">
  </form>
</div>
{% endblock %}

summaryapp/templates/summaryapp/create.html
{% extends 'base.html' %}
{% load bootstrap4 %}
{% block content %}

<div style="text-align: center; max-width: 500px; margin: 4rem auto;">
  <div class="mb-4">
    <h3>Sighup</h3>
  </div>
  <form action="{% url 'summaryapp:create' %}" method="post">
    {% csrf_token %}
    {% bootstrap_form form %}
    <input type="submit" class="btn btn-dark rounded-pill col-6 mt-3" value="회원가입">
  </form>
</div>
{% endblock %}

summaryapp/templates/summaryapp/delete.html
{% extends 'base.html' %}

{% block content %}

<div style="text-align: center; max-width: 500px; margin: 4rem auto;">
  <div class="mb-4">
    <h3>Quit</h3>
  </div>
  <form action="{% url 'summaryapp:delete' pk=target_user.pk %}" method="post">
    {% csrf_token %}
    <input type="submit" class="btn btn-dark rounded-pill col-6 mt-3" value="탈퇴">
  </form>
</div>
{% endblock %}

summaryapp/templates/summaryapp/detail.html
{% extends 'base.html' %}
{% block content %}

{% if not user.is_authenticated %}
<div style="text-align: center; height: 20rem;">
    <a href="{% url 'summaryapp:index' %}" style="text-decoration: none;">
        <h1 class="god_logo" style="margin-top: 15rem; text-decoration: none; color: black;">Guardians of data</h1>
    </a>
</div>
{% else %}
<div>
    <div style="text-align: center; max-width: 500px; margin: 4rem auto;">

        {% if target_user.profile %}
        <img src="{{ target_user.profile.image.url }}" alt=""
             style="height: 10rem; width: 10rem; border-radius: 20rem; margin-bottom: 2rem;">
        <h2>
            {{ target_user.profile.nickname }}
            {% if target_user == user %}
            <a href="{% url 'profileapp:update' pk=target_user.profile.pk %}">
                edit
            </a>
            {% endif %}
        </h2>
        <h5 style="margin-bottom: 3rem;">
            {{ target_user.profile.message }}
        </h5>
        {% else %}
        {% if target_user == user %}
        <a href="{% url 'profileapp:create' %}">
            <h2>
                Create Profile
            </h2>
        </a>
        {% endif %}
        {% endif %}


        {% if target_user == user %}
        <a href="{% url 'summaryapp:update' pk=target_user.pk %}">
            <p>
                Change Info
            </p>
        </a>
        <a href="{% url 'summaryapp:delete' pk=target_user.pk %}">
            <p>
                Quit
            </p>
        </a>
        {% endif %}
    </div>
</div>
{% endif %}
{% endblock%}

summaryapp/templates/summaryapp/index.html
{% extends 'base.html' %}

{% block content %}
<div class="container">
    <h3 class="god_logo_input">요약할 기사를 입력해 주세요.</h3>
    <div style="text-align: left; margin : 1rem 7rem;">
        <div class="form-check form-check-inline">
            <input type="checkbox" name="chk1" value="1" class="form-check-input cursor-pointer" id="classification1">
            <label for="classification1" class="form-check-label cursor-pointer" style="cursor:pointer">경제</label>
        </div>
        <div class="form-check form-check-inline">
            <input type="checkbox" name="chk2" value="1" class="form-check-input cursor-pointer" id="classification2">
            <label for="classification2" class="form-check-label cursor-pointer" style="cursor:pointer">정치</label>
        </div>
        <div class="form-check form-check-inline">
            <input type="checkbox" name="chk3" value="1" class="form-check-input cursor-pointer" id="classification3">
            <label for="classification3" class="form-check-label cursor-pointer" style="cursor:pointer">연애</label>
        </div>
        <div class="form-check form-check-inline">
            <input type="checkbox" name="chk4" value="1" class="form-check-input cursor-pointer" id="classification4">
            <label for="classification4" class="form-check-label cursor-pointer" style="cursor:pointer">스포츠</label>
        </div>
    </div>
    <div class="god_search">
        <form action="/summarys/crawling/" method="post">
            {% csrf_token %}
            <input type="text" name="crawling_input">
            <input type="submit">
        </form>
    </div>
    <div class="flex-container">
        <form action="/summarys/index/" method="post">
            <div class="god-box">
                {% if crawling_data %}
                <textarea class="god_textarea" name="summary_input">{{ crawling_data.text }}</textarea>
                {% endif %}
            </div>
            <div style="width: 3rem; height: 3rem; margin-left: 27rem; margin-top: -17rem;">
                {% csrf_token %}
                <button type="submit"
                        style="border: none; outline: none; background-color: #ffffff; margin: 1rem auto;">
                    <i class="fa-solid fa-arrow-right arrow-icon" style="font-size: 2rem;"></i>
                </button>
            </div>

        </form>
        <div style="margin: 1rem 1rem;"></div>
        <div class="god-box">
            {% if summary_output %}
            <textarea class="god_textarea">{{ summary_output.text }}</textarea>
            {% endif %}
        </div>


    </div>

</div>
<div class="flex-container">
    <div style="width: 18rem; border: 1px solid #dae1e8; border-radius: 8px; margin: auto 1rem;">
        <div class="card-body">
            <h5 class="card-title">Card title</h5>
            <h6 class="card-subtitle mb-2 text-muted">Card subtitle</h6>
            <p class="card-text">Some quick example text to build on the card title and make up the bulk of the
                card's
                content.</p>
            <a href="#" class="card-link">Card link</a>
        </div>
    </div>

    <div style="width: 18rem; border: 1px solid #dae1e8; border-radius: 8px; margin: auto 1rem;">
        <div class="card-body">
            <h5 class="card-title">Card title</h5>
            <h6 class="card-subtitle mb-2 text-muted">Card subtitle</h6>
            <p class="card-text">Some quick example text to build on the card title and make up the bulk of the
                card's
                content.</p>
            <a href="#" class="card-link">Card link</a>
        </div>
    </div>
    <div style="width: 18rem; border: 1px solid #dae1e8; border-radius: 8px; margin: auto 1rem;">
        <div class="card-body">
            <h5 class="card-title">Card title</h5>
            <h6 class="card-subtitle mb-2 text-muted">Card subtitle</h6>
            <p class="card-text">Some quick example text to build on the card title and make up the bulk of the
                card's
                content.</p>
            <a href="#" class="card-link">Card link</a>
        </div>
    </div>
</div>
{% endblock %}

summaryapp/templates/summaryapp/login.html
{% extends 'base.html' %}
{% load bootstrap4 %}

{% block content %}
<div style="text-align:center; max-width: 500px; margin: 4rem auto;">
    <div>
        <h4>login</h4>
    </div>
    <div>
        <form action="" method="post">
            {% csrf_token %}
            {% bootstrap_form form %}
            <input type="submit" class="btn btn-dark rounded-pill col-6 mt-3" value="로그인"> <!-- col : 너비 설정, mt : margin-top -->
        </form>
    </div>
</div>

{% endblock %}

summaryapp/templates/summaryapp/update.html
{% extends 'base.html' %}
{% load bootstrap4 %}
{% block content %}

<div style="text-align: center; max-width: 500px; margin: 4rem auto;">
  <div class="mb-4">
    <h3>Change Info</h3>
  </div>
  <form action="{% url 'summaryapp:update' pk=target_user.pk%}" method="post">
    {% csrf_token %}
    {% bootstrap_form form %}
    <input type="submit" class="btn btn-dark rounded-pill col-6 mt-3">
  </form>
</div>
{% endblock %}

templates/base.html
<!DOCTYPE html>
<html lang="en">
{% include 'head.html' %}
<body>

<!-- header 부분 -->
{% include 'header.html' %}
<hr>

{% block content %}
{% endblock %}
<hr>
<!-- footer 부분 -->
{% include 'footer.html' %}
</body>
</html>

templates/footer.html
<div class="god_footer">
    <div class="god_footer_button">
        <span>회사소개</span> |
        <span>이용약관</span> |
        <span>광고문의</span> |
        <span>개인정보처리방침</span> |
        <span>고객센터</span>
    </div>
    <div style="margin-top: 1rem;">
        <h5 class="god_logo">Guardians of data</h5>
    </div>
</div>

templates/head.html
{% load static%}

<head>
    <meta charset="UTF-8">

    <title>Guardians of data</title>

    <!--  BOOTSTRAP LINK  -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/css/bootstrap.min.css"
          integrity="sha384-xOolHFLEh07PJGoPkLv1IbcEPTNtaed2xpHsD9ESMhqIYd0nLMwNLD69Npy4HI+N" crossorigin="anonymous">

    <!--  GOOGLE FONT LINK  -->
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Anton&family=Dancing+Script&display=swap" rel="stylesheet">

    <!-- DEFAULT CSS LINK -->
    <link rel="stylesheet" href="{% static 'base.css' %}">

    <!--  font-awesome icon  -->
    <script src="https://kit.fontawesome.com/4c83192391.js" crossorigin="anonymous"></script>
</head>

templates/header.html
<div class="god_footer">
    <div>
        <h1 class="god_logo">Guardians of data</h1>
    </div>
    <div>
        <span>제태성</span>
        <span>김학진</span>
        <span>박병준</span>
        <span>박소연</span>
        <span>오수연</span>
        {% if not user.is_authenticated %}
        <a href="{% url 'summaryapp:login' %}?next={{ request.path }}"> <!-- 로그인 후 원래 페이지로 돌아옴 -->
            <span>login</span>
        </a>
        <a href="{% url 'summaryapp:create' %}"> <!-- 로그인 후 원래 페이지로 돌아옴 -->
            <span>signup</span>
        </a>
        {% else %}
        <a href="{% url 'summaryapp:detail' pk=user.pk %}"> <!-- 로그아웃 후 원래 페이지로 돌아옴 -->
            <span>mypage</span>
        </a>
        <a href="{% url 'summaryapp:logout' %}?next={{ request.path }}"> <!-- 로그아웃 후 원래 페이지로 돌아옴 -->
            <span>logout</span>
        </a>
        {% endif %}
    </div>
</div>